apiVersion: apps/v1 
kind: Deployment
metadata:
  name: library-api-app-deployment
  labels:
    app: library-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-api
  template:
    metadata:
      labels:
        app: library-api
    spec:
      containers:
      - name: library-api
        image: distributedsystems:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080

